(setq yas-prompt-functions '(yas/dropdown-prompt yas/ido-prompt))
(setq yas-fallback-behavior 'return-nil)
(define-key yas-minor-mode-map [(tab)] nil)
(define-key yas-minor-mode-map (kbd "TAB") nil)
(global-set-key (kbd "C-?") 'yas-expand)
