(setq dash-at-point-mode-alist '((ruby-mode . "Ruby")
                                 (js2-mode . "JavaScript")
                                 (coffee-mode . "JavaScript")
                                 (css-mode . "CSS")
                                 (less-css-mode . "CSS")
                                 (sass-mode . "CSS")
                                 (html-mode . "HTML")
                                 (scala-mode . "Java")
                                 (java-mode . "Java")))
