(auto-complete-mode)
(local-set-key (kbd "RET") 'newline-and-indent)
(setq web-mode-markup-indent-offset 2)
(setq web-mode-css-indent-offset 2)
(setq web-mode-code-indent-offset 2)
(setq web-mode-indent-style 2)